version: '3.8'

services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public

  static-web:
    build: ./static-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.services.static.loadbalancer.server.port=80"
    networks:
      - gd-network
      - traefik-public

  api:
    build: ./api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
    networks:
      - gd-network
      - traefik-public

networks:
  gd-network:
    driver: bridge
  traefik-public:
    external: true
