api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

tls:
  certificates:
    - certFile: "/etc/traefik/certificates/cert.crt"
      keyFile: "/etc/traefik/certificates/cert.key"
